// Styling for UK Passport Check page, matching the non-UK RTW page
export const styles = {
  page: { minHeight: "100vh", background: "#000", color: "white" },
  container: {
    maxWidth: 640,
    margin: "0 auto",
    padding: "32px 24px 40px",
    background: "#18181b",
    borderRadius: 18,
    boxShadow: "0 4px 32px rgba(0,0,0,0.12)",
  },
  title: { fontSize: 28, fontWeight: 800, marginBottom: 6 },
  subtitle: { opacity: 0.85, marginTop: 6, maxWidth: 960, marginInline: "auto" },
  form: {
    display: "grid",
    gap: 18,
    gridTemplateColumns: "1fr 1fr",
    marginTop: 24,
  },
  col: { display: "flex", flexDirection: "column", gap: 8 },
  label: {
    color: "#e5e7eb",
    fontSize: 13,
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 2,
  },
  input: {
    width: "100%",
    padding: "12px 16px",
    borderRadius: 18,
    border: "1px solid #374151",
    backgroundColor: "#111827",
    color: "#e5e7eb",
    fontSize: 14,
    outline: "none",
    transition: "box-shadow 120ms ease, border-color 120ms ease",
  },
  inputFocus: { boxShadow: "0 0 0 2px rgba(96,165,250,0.45)" },
  select: {
    width: "100%",
    padding: "12px 16px",
    borderRadius: 18,
    border: "1px solid #374151",
    backgroundColor: "#111827",
    color: "#e5e7eb",
    fontSize: 14,
    outline: "none",
  },
  checkbox: { marginTop: 2 },
  button: {
    padding: "14px 16px",
    background: "#60a5fa",
    color: "#0b0f1a",
    borderRadius: 12,
    border: "none",
    fontWeight: 800,
    cursor: "pointer",
    marginTop: 8,
  },
  error: { color: "#fca5a5", fontSize: 13, marginTop: 4 },
  message: { color: "#e5e7eb", fontSize: 14, marginTop: 8 },
  info: { color: "#9ca3af", fontSize: 12, marginTop: 16 },
};
